### ISSUE TITLE
Enable yaml anchor resolver in spectral

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/oas-spectral-validator#1]
## I expect

yaml anchors are resolved, eg:

```
x-commons:
  ratelimit: &ratelimit
    X-RateLimit-Limit: {}

components:
  headers:
    <<: *ratelimit
```

## Instead

They are not.
